# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Rotwild
tagline:          ‘@rtwld’
description:      ‘Pseudonymous academics. I like to test (and break) stuff, mostly ideas. #philosophy #hacking #science’
url:              http://rtwld.github.io/blog
baseurl:          http://rtwld.github.io/blog

author:
  name:           ‘Rotwild’
  url:            https://twitter.com/rtwld

paginate:         5

# Custom vars
version:          2.1.0

github:		  https://github.com/rtwld
